platform=local
environment=qa
# qa or uat

qaurl=https://juice-shop.herokuapp.com/
uaturl=https://juice-shop.herokuapp.com/
chromedriver="src/test/resources/chromedriver.exe"
edgedriver="src/test/resources/msedgedriver.exe"
